data_source:
  directory: "./Dataset/"         # Path to the dataset folder
  filename: "winequality-red.csv"  # Name of the dataset file (note the key: 'filename')
  random_state: 42  # You can change this to any integer you want
  test_size: 0.2        # 20% of the data for testing, 80% for training


model_2:
  n_estimator: 100             # Number of trees in the random forest
  scoring: "recall"            # Scoring metric for cross-validation (can be "accuracy", "precision", etc.)
  cv: 5                        # Number of folds in cross-validation
  verbose: 1                   # Verbose level for cross-validation output
  n_jobs: -1                   # Use all available cores for parallel processing